weifilm/app/home/forms.py
#coding:utf8
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SelectField,SelectMultipleField,SubmitField,TextAreaField,TextField,PasswordField,FileField
from wtforms.validators import DataRequired,ValidationError,EqualTo,Email,Regexp
from app.models import User

class RegisterForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称!")
        ],
        description="昵称",
        render_kw={
            "class":"form-control input-lg" ,
            "placeholder":"请输入昵称！",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱!"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机号码",
        validators=[
            DataRequired("请输入手机号码!"),
            Regexp('1[345789]\\d{9}',message='手机号码格式不正确')
        ],
        description="手机号码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码！",
        }
    )
    pwd = PasswordField(
        label = "密码",
        validators=[
            DataRequired("请输入密码！"),
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
            # "required": "required"
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('pwd',message='两次密码不一致！')
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码！",
            # "required": "required"
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-primary btn-block btn-flat",
        }
    )
    def validate_account(self,field):
        account = field.data
        admin = User.query.filter_by(name=account).count()
        if admin == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self,field):
        account = field.data
        admin = User.query.filter_by(email=account).count()
        if admin == 1:
            raise ValidationError("邮箱已经被注册！")
    def validate_phone(self,field):
        account = field.data
        admin = User.query.filter_by(phone=account).count()
        if admin == 1:
            raise ValidationError("手机号已经被注册！")

class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号!")
        ],
        description="账号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号！",
            # "required":"required"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码！",
            # "required": "required"
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-primary btn-block btn-flat",
        }
    )

    def validate_account(self, field):
        account = field.data
        admin = User.query.filter_by(name=account).count()
        if admin == 0:
            raise ValidationError("账号不存在!")

class UserdetailForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称!")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱!"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机号码",
        validators=[
            DataRequired("请输入手机号码!"),
            Regexp('1[345789]\\d{9}', message='手机号码格式不正确')
        ],
        description="手机号码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码！",
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像!"),
        ],
        description="头像",
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介!"),
        ],
        description="简介",
        render_kw={
            "class": "form-control input-lg",
            'rows':10
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )
class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码！",
            # "required": "required"
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！",
            # "required": "required"
        }
    )
    submit = SubmitField(
        '修改',
        render_kw={
            "class": "btn btn-primary",
        }
    )
    def validate_old_pwd(self,field):
        from flask import session
        pwd = field.data
        name = session['user']
        user = User.query.filter_by(
            name=name
        ).first()
        if not user.check_pwd(pwd):
            raise ValidationError("旧密码错误！")

class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入评论内容！")
        ],
        description="内容",
        render_kw={
            "id":"btn-sub",
            # "required": "required"
        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            "class": "btn btn-success",
            "id":"btn-sub"
        }
    )

weifilm/app/home/__init__.py
#coding:utf8
from flask import Blueprint

home = Blueprint('home',__name__)

import app.home.views

weifilm/app/home/views.py
#coding:utf8
from . import home
from flask import render_template, redirect, url_for, flash, session, request, jsonify, json
from .forms import RegisterForm,LoginForm,UserdetailForm,PwdForm,CommentForm
from app.models import User,Userlog,Preview,Tag,Comment,Moviecol,Movie
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import db,app
from uuid import uuid4
from functools import wraps
import datetime
import os

#登录装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args,**kwargs):
        if 'user' not in session:
            return redirect(url_for('home.login',next=request.url))
        return  f(*args,**kwargs)
    return decorated_function

# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + uuid4().hex + fileinfo[-1]
    return filename


@home.route('/<int:page>/',methods=['GET','POST'])#基础页面
def index(page=None):
    tags = Tag.query.all()
    page_data = Movie.query
    #标签
    tid = request.args.get('tid',0)
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id = int(tid))
    #星级
    star = request.args.get('star',0)
    if int(star) != 0:
        page_data = page_data.filter_by(star = int(star))
    #时间
    time = request.args.get('time', 0)
    if int(time) != 0:
        if int(time) == 1 :
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
    #播放量
    pm = request.args.get('pm', 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    #评论量
    cm = request.args.get('cm', 0)
    if int(cm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.commentnum.asc()
            )
    if page==None:
        page=1
    page_data = page_data.paginate(page=page,per_page=10)
    p = dict(
        tid=tid,
        star=star,
        pm=pm,
        cm=cm,
        time=time
    )
    return render_template('home/index.html',tag=tags,p=p,page_data=page_data)

@home.route('/login/',methods=['GET','POST'])#登录页面
def login():
    form = LoginForm()
    if request.method=='GET':
        form.name.data = request.args.get('name')

    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name = data['name']).first()
        user_count = User.query.filter_by(name=data['name']).count()
        if user_count == 0:
            flash('用户名不存在！', 'err')
            return redirect(url_for('home.login'))
        if not user.check_pwd(data['pwd']):
            flash('密码错误！','err')
            return redirect(url_for('home.login',name=user.name))
        session['user'] = user.name
        session['user_id'] = user.id
        userlog = Userlog(
            user_id=user.id,
            ip = request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for('home.user'))
    return render_template('home/login.html',form=form)

@home.route('/logout/')#退出页面
@user_login_req
def logout():
    session.pop('user_id',None)
    session.pop('user',None)
    return redirect(url_for('home.login'))

@home.route('/register/',methods=['GET','POST'])#注册页面
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name = data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功！','ok')
    return render_template('home/register.html',form=form)

@home.route('/user/',methods=['GET','POST'])#会员中心
@user_login_req
def user():
    form = UserdetailForm()
    user = User.query.get(session['user_id'])
    form.face.validators=[]
    form.info.validators = []
    if request.method=='GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if not os.path.exists(app.config['FC_DIR']):
            os.makedirs(app.config['FC_DIR'])
            os.chmod(app.config['FC_DIR'], "rw")
        if form.face.data.filename!='':
            if user.face:
                file_face = secure_filename(form.face.data.filename)
                os.remove(app.config['FC_DIR'] + user.face + '.png')
                user.face = change_filename(file_face)
                user.face.data.save(app.config['FC_DIR'] + user.face + '.png')
            else:
                user.face = change_filename(form.face.data.filename)
                form.face.data.save(app.config['FC_DIR'] + user.face + '.png')
        email_count = User.query.filter_by(email=data['email']).count()
        if email_count == 1 and user.email != data['email']:
            flash("邮箱已被注册！", 'err')
            return redirect(url_for("home.user"))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if phone_count == 1 and user.phone != data['phone']:
            flash("手机号码已被注册！", 'err')
            return redirect(url_for("home.user"))

        name_count = User.query.filter_by(name=data['name']).count()
        if name_count == 1 and user.name != data['name']:
            flash("昵称已存在！", 'err')
            return redirect(url_for("home.user"))

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        print( user.uuid )

        db.session.add(user)
        db.session.commit()
        flash('修改成功！','ok')
        return redirect(url_for('home.user'))
    return render_template('home/user.html',form=form,user=user)

@home.route('/pwd/',methods=['GET','POST'])#修改密码
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session['user']).first()
        from werkzeug.security import generate_password_hash
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登录！", 'ok')
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html", form=form)


@home.route('/comments/<int:page>')#评论记录
@user_login_req
def comments(page=None):
    if page is None:
        page=1
    id = session['user_id']
    page_data = Comment.query.join(User).filter(
        User.id==id,
        User.id==Comment.user_id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page,per_page=10)
    return render_template('home/comments.html',page_data=page_data)

@home.route('/loginlog/<int:page>/',methods=['GET','POST'])#登录日志
@user_login_req
def loginlog(page):
    if page is None:
        page = 1
    page_data = Userlog.query.join(
        User
    ).filter(
        User.id==session['user_id'],
        User.id==Userlog.user_id,
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page,per_page=10)
    return render_template("home/loginlog.html",page_data=page_data)

@home.route('/moviecol/<int:page>/')#收藏电影
@user_login_req
def moviecol(page=None):
    if page is None:
        page=1
    id = session['user_id']
    page_data = Moviecol.query.join(User).join(Movie).filter(
        Movie.id == Moviecol.movie_id,
        User.id == id,
        User.id == Moviecol.user_id
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page,per_page=10)
    return render_template('home/moviecol_list.html',page_data=page_data)

@home.route('/moviecoladd/',methods=['POST'])#添加收藏电影
def moviecoladd():
    if request.method=='POST':
        data = json.loads(request.form.get('data'))
        name = str(data['username'])
        movie_id = int(data['movie_id'])
        movie = Movie.query.get(movie_id)

        moveicol_count = Moviecol.query.join(User).join(Movie).filter(
            User.id==Moviecol.user_id,
            Movie.id==Moviecol.movie_id,
            Movie.id==movie_id,
            User.name==name
        ).count()
        if moveicol_count == 0 :
            user = User.query.filter(User.name==name).first()
            moviecol = Moviecol(
                user_id=user.id,
                movie_id=movie_id,
                addtime=datetime.datetime.now()
            )
            db.session.add(moviecol)
            db.session.commit()
            return jsonify({'msg': '添加收藏成功！'})
        else:
            return jsonify({'msg': '添加收藏失败，《'+movie.title+'》已被收藏！'})




@home.route('/animation/')
def animation():
    data = Preview.query.all()
    count=0
    return render_template('home/animation.html',data=data,count=count)

@home.route('/search/<int:page>')
def search(page=None):
    if page==None:
        page=1
    key = request.args.get('key','')
    page_data = Movie.query.filter(
        Movie.title.like('%'+key+'%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page,per_page=10)
    count = Movie.query.filter(
        Movie.title.like('%'+key+'%')
    ).count()
    return render_template('home/search.html',key=key,page_data=page_data,count=count)

@home.route('/play/<int:id>/<int:page>',methods=['GET','POST'])
def play(id=None,page=None):
    movie = Movie.query.join(Tag).filter(Tag.id == Movie.tag_id, Movie.id == id).first()
    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        User.id == Comment.user_id,

weifilm/app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='anim/css/style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='base/css/iconfont.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
<!--				<span class="banner_btn_arrow"><i class="iconfont icon-left-1"></i></span>-->
				<span class="iconfont icon-left-1"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
<!--				<span class="banner_btn_arrow"><i></i></span>-->
				<span class="iconfont icon-right-1-copy"><i></i></span>
			</a>
			<ul>
				{% for v in data %}
				<li id="imgCard{{ v.id-1 }}">
					<a href=""><span style="opacity:0;"></span></a>
					<img src="{{ url_for('static',filename='uploads/'+v.logo+'.png')}}" alt="">
					<p style="bottom:0">{{ v.title }}</p>
				</li>
				{% endfor %}

			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="{{ url_for('static',filename='anim/js/script.js') }}"></script>

</body>
</html>

weifilm/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-ba r"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <strong>版权 &copy; 2021-2022 归<a href="">B19160217杨周辰</a>.</strong> 所有
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
    $('#do_search').click(function () {
        var key = $('#key_movie').val();
        location.href = "{{ url_for('home.search',page=1) }}?key=" + key;
    })

</script>
{% block js %}{% endblock %}
</body>
</html>

weifilm/app/templates/home/index.html
{% extends "home/layout.html" %}
{% import "ui/home_page.html" as pg%}
{% block content %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                        src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for v in tag %}
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ v.id }}&&star={{ p['star']}}&&time={{ p['time']}}&&pm={{ p['pm']}}&&cm={{ p['cm']}}" class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{ v.name }}</a>
                            {% endfor %}
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for v in range(1,6) %}
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ v }}&&time={{ p['time']}}&&pm={{ p['pm']}}&&cm={{ p['cm']}}" class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ v }}星</a>
                           {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ p['star']}}&&time=1&&pm={{ p['pm']}}&&cm={{ p['cm']}}" class="label label-default"><span
                                    class="glyphicon glyphicon-time"></span>&nbsp;最近</span></a>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid']}}&&star={{ p['star']}}&&time=2&&pm={{ p['pm']}}&&cm={{ p['cm']}}" class="label label-default"><span
                                    class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                            &nbsp;

                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ p['star']}}&&time={{ p['time']}}&&pm=1&&cm={{ p['cm']}}" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ p['star']}}&&time={{ p['time']}}&&pm=2&&cm={{ p['cm']}}" class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ p['star']}}&&time={{ p['time']}}&&pm={{ p['pm']}}&&cm=1" class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                            </a>
                            &nbsp;
                            <a href="{{ url_for('home.index',page=1)}}?tid={{ p['tid'] }}&&star={{ p['star']}}&&time={{ p['time']}}&&pm={{ p['pm']}}&&cm=2" class="label label-danger"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="{{ url_for('static',filename='uploads/'+v.logo+'.png')}}" width="262px" height="380px" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                        <div>
                            {% for v in range(1,v.star+1) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                            {% for v in range(1,5-v.star+1) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            {% endfor %}

                        </div>
                    </div>
                    <a href="{{ url_for('home.play',id=v.id,page=1) }}" class="btn btn-primary" target="_blank" role="button"><span
                            class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                {{ pg.page(page_data,"home.index")}}
            </div>
        </div>
    </div>
</section>
{% endblock %}

weifilm/app/templates/home/search.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg%}
{% block content %}
<div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;">
                <li>与"{{ key }}"有关的电影，共{{ count }}部</li>
            </ol>
        </div>
        <div class="col-md-12">
            {% for v in page_data.items %}
            <div class="media">
                <div class="media-left">
                    <a href="{{ url_for('home.play',id=v.id,page=1) }}">
                        <img class="media-object" width="131px" height="83px" src="{{ url_for('static',filename='uploads/'+v.logo+'.png' ) }}" alt="{{ v.title }}">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ v.title }}<a href="{{ url_for('home.play',id=v.id,page=1) }}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                    <textarea overflow-y="scroll" cols="132" rows="3">{{ v.info }}</textarea>
                </div>
            </div>
           {% endfor %}
        </div>
        <div class="col-md-12 text-center">
            {{ pg.page(page_data,"home.search")}}
        </div>
    </div>
{% endblock %}